import pandas as pd
import os

def generate_markdown_report():
    # Define paths
    csv_path = 'reports/dataset_yucatan.csv'
    plot_path = 'reports/insecurity_trend_yucatan.png' # This plot is generated by the previous script
    report_path = 'reports/reporte_analisis_yucatan.md'

    # --- Read and Prepare Data ---
    if not os.path.exists(csv_path):
        print(f"Error: {csv_path} not found. Please generate it first.")
        return
    df = pd.read_csv(csv_path)

    df['PERIODO'] = df['AÑO'].astype(str) + '-Q' + df['TRIMESTRE'].astype(str)
    df_sorted = df.sort_values(by=['AÑO', 'TRIMESTRE'])

    df_sorted['INSEGUROS_PONDERADO'] = df_sorted['PCT_INSEGUROS'] * df_sorted['TOTAL_REGISTROS']
    state_level = df_sorted.groupby('PERIODO').agg(
        SUMA_INSEGUROS_PONDERADO=('INSEGUROS_PONDERADO', 'sum'),
        SUMA_TOTAL_REGISTROS=('TOTAL_REGISTROS', 'sum')
    ).reset_index()

    state_level['PCT_INSEGURIDAD_ESTATAL'] = state_level['SUMA_INSEGUROS_PONDERADO'] / state_level['SUMA_TOTAL_REGISTROS']
    state_level = state_level.sort_values(by='PERIODO')
    state_level['PCT_INSEGURIDAD_ESTATAL_FORMAT'] = state_level['PCT_INSEGURIDAD_ESTATAL'].apply(lambda x: f'{x:.1%}')

    # --- Build Markdown Report ---
    md_content = """
# Análisis de Percepción de Inseguridad en Yucatán

Este reporte presenta la evolución de la percepción de inseguridad en el estado de Yucatán, basada en los datos procesados de la ENSU. 
La métrica principal es el porcentaje de la población que percibe su entorno como inseguro, ponderado por el número de encuestados en cada municipio para obtener una visión a nivel estatal.

## Datos Agregados por Periodo

A continuación se muestra la tabla con el porcentaje de percepción de inseguridad a nivel estatal para cada periodo:

"""
    # Add the data table to the markdown content
    md_content += state_level[['PERIODO', 'PCT_INSEGURIDAD_ESTATAL_FORMAT']].to_markdown(index=False)
    md_content += "\n\n"

    # Add the plot to the markdown content
    md_content += """
## Evolución de la Percepción de Inseguridad

La siguiente gráfica ilustra la tendencia a lo largo del tiempo.

"""
    if os.path.exists(plot_path):
        md_content += f"![Evolución de la Inseguridad en Yucatán]({os.path.basename(plot_path)})"
    else:
        md_content += "*Gráfica no encontrada. Por favor, ejecute el script 04_analyze_yucatan.py para generarla.*\n"

    # --- Conclusion ---
    first_val = state_level['PCT_INSEGURIDAD_ESTATAL'].iloc[0]
    last_val = state_level['PCT_INSEGURIDAD_ESTATAL'].iloc[-1]
    peak_val = state_level['PCT_INSEGURIDAD_ESTATAL'].max()
    peak_period = state_level.loc[state_level['PCT_INSEGURIDAD_ESTATAL'].idxmax(), 'PERIODO']

    conclusion_text = f"""
El análisis de los datos desde {state_level['PERIODO'].iloc[0]} hasta {state_level['PERIODO'].iloc[-1]} revela varias tendencias clave en la percepción de inseguridad en Yucatán.

El punto más alto de inseguridad percibida se registró en el periodo **{peak_period}**, alcanzando un **{peak_val:.1%}**.
"""
    if last_val > first_val:
        conclusion_text += "En general, la gráfica muestra una **tendencia al alza** en la percepción de inseguridad a lo largo del tiempo, a pesar de fluctuaciones trimestrales."
    else:
        conclusion_text += "En general, la gráfica muestra una **tendencia a la baja** en la percepción de inseguridad a lo largo del tiempo, a pesar de fluctuaciones trimestrales."

    md_content += "\n\n## Conclusión\n\n" + conclusion_text

    # --- Save Markdown File ---
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(md_content)
    
    print(f"Markdown report successfully generated at: {report_path}")

if __name__ == '__main__':
    generate_markdown_report()
